[package]
name = "torqa-video"
description = "Video decoding for Torqa's video ride mode, built on FFmpeg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ffmpeg-next.workspace = true
quick-xml.workspace = true
rav1d.workspace = true
thiserror.workspace = true

[features]
# Test videos for other crates' tests.
testing = []

[lints]
workspace = true
